name: calamity_report
description: A Flutter emergency reporting application

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0 # Ensure the intl package is added
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^17.0.0
  
  # Media & Location
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.4+2
  location: ^5.0.0
  image_picker: ^1.1.5
  video_player: ^2.9.1
  chewie: ^1.8.3
  http: ^1.1.0
  
  # Audio
  flutter_sound: ^9.2.13
  permission_handler: ^12.0.1
  audio_session: ^0.2.2
  path_provider: ^2.1.4
  
  # Utilities
  path: ^1.9.0
  location_platform_interface: 3.1.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  cloud_functions: ^6.0.4
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^18.0.1
  cloud_firestore: 6.1.0
  cached_network_image: ^3.3.0
  fl_chart: ^0.65.0

  # Photo View
  photo_view: ^0.14.0
  geolocator: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pins.json
